### ISSUE TITLE
"runIntervalMinutes" config value causes a panic

### ISSUE THREAD

**Issue by spideyfusion** [lpredova/njuhalo#30]
Hey,

If you set the `runIntervalMinutes` config option to anything other than a `1` the program will crash with the following stack trace:

```sh
panic: 

goroutine 1 [running]:
github.com/lpredova/njuhalo/vendor/github.com/jasonlvhit/gocron.(*Job).Minute(...)
	/projects/src/github.com/lpredova/njuhalo/vendor/github.com/jasonlvhit/gocron/gocron.go:216
github.com/lpredova/njuhalo/command.StartMonitoring()
	/projects/src/github.com/lpredova/njuhalo/command/command.go:81 +0x2b5
main.init.0.func2(0xc0000d89a0, 0x0, 0xc0000d89a0)
	/projects/src/github.com/lpredova/njuhalo/main.go:41 +0x20
github.com/lpredova/njuhalo/vendor/github.com/urfave/cli.HandleAction(0x8afae0, 0x964700, 0xc0000d89a0, 0xc00006e500, 0x0)
	/projects/src/github.com/lpredova/njuhalo/vendor/github.com/urfave/cli/app.go:502 +0xc8
github.com/lpredova/njuhalo/vendor/github.com/urfave/cli.Command.Run(0x94ae18, 0xc, 0x0, 0x0, 0xc000042e40, 0x1, 0x1, 0x956ad0, 0x23, 0x0, ...)
	/projects/src/github.com/lpredova/njuhalo/vendor/github.com/urfave/cli/command.go:210 +0x9aa
github.com/lpredova/njuhalo/vendor/github.com/urfave/cli.(*App).Run(0xc00013a380, 0xc00000c080, 0x2, 0x2, 0x0, 0x0)
	/projects/src/github.com/lpredova/njuhalo/vendor/github.com/urfave/cli/app.go:259 +0x6bb
main.main()
	/projects/src/github.com/lpredova/njuhalo/main.go:94 +0x51

```

Following it leads us to the `goCron` package:

https://github.com/jasonlvhit/gocron/blob/master/gocron.go#L247

Here you can notice that a panic is triggered for the exact case that I mentioned. Turns out, you should be using the [Minutes()](https://godoc.org/github.com/jasonlvhit/gocron#Job.Minutes) function instead:

```go
gocron.Every(uint64(conf.RunIntervalMin)).Minutes().Do(runParser)
```

vs

```go
gocron.Every(uint64(conf.RunIntervalMin)).Minute().Do(runParser)
```

I stumbled upon this because the default value gets set to `5` when you generate a new configuration file. :-)

**Comment by lpredova** [comment]
Hey @spideyfusion ! Kudos to you!

This issue will be fixed in 2.0 version which is about to come 😃
